#!/usr/bin/env python3
"""#334 STEP 6b — PUBLISH THE STAGE-A BOARD, on the owner's landing word ("land and rederive").

The #328 step-6b pattern, re-pointed rather than rewritten. The reasoning is the same and it is
worth restating, because it is a correction to this act's own earlier deferral: while no board was
published, leaving `data/rl_build/*.srcmd5` and the `ui/data` bundles at the old store was coherent.
Publishing the board ends that, and the project's own guard (`ui/tools/ownership_store_apply.py`,
P3) would report INCOHERENT BASE across the six store-identity carriers if it did not move here:

    "If the tree already disagrees with itself about which store it is on, moving the pin would
     paper over the disagreement instead of surfacing it."

WHAT MOVES, AND NOTHING ELSE
  1  data/rl_build/rl_app_data.json          the canonical build's OWN output, mirrored in whole
     data/rl_build/rl_app_data.json.srcmd5   the sidecar the build's own writer
                                             (single_source.stamp_derived) already stamped in the
                                             workspace — MIRRORED, never hand-written here
  2  data/expected_boot.json  'board'        864b6726 -> 827fb1fd  (surgical, byte-preserving)
  3  data/release_contract.json identities.board + contract_sha256 recomputed by the contract's
                                             OWN writer (release_contract.contract_hash)
  4  ui/data/*                               regenerated by ui/tools/extract_board_view.py, whose
                                             RING-FENCE asserts refuse until pins 2 and 3 have moved

DELIBERATELY NOT MOVED: `balanced_board_md5` (4939d740) — a separate artifact, and no balanced
reference is built here. `data/release_lineage.json` — sealed history.

  python3 publish_board_334.py <REPO> <WORKSPACE_RL_AFTER> [--apply]
"""
import hashlib, importlib.util, json, os, shutil, stat, sys

REPO = sys.argv[1].rstrip('/')
WS = sys.argv[2].rstrip('/')
APPLY = '--apply' in sys.argv
P = lambda *a: os.path.join(REPO, *a)

OLD_BOARD = '864b6726a4612b0d8afe57f230421514'
NEW_BOARD = '827fb1fdfefe60c7c2c9026212d3992d'
STORE = 'f1e7f20c4adea9b17d19457a5217c735'


def md5(p):
    return hashlib.md5(open(p, 'rb').read()).hexdigest()


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m); return m


def write_json_preserving(path, obj):
    """Same discipline as the store-pin re-stamp: prove the untouched file round-trips
    byte-identically under this writer BEFORE writing, so the diff carries the intended fields and
    no reformatting rides along."""
    original = open(path, 'rb').read()
    tail = '\n' if original.endswith(b'\n') else ''
    if (json.dumps(json.load(open(path)), indent=1) + tail).encode() != original:
        raise SystemExit('HALT: %s does not round-trip byte-identically' % path)
    with open(path, 'w') as f:
        f.write(json.dumps(obj, indent=1) + tail)


# ---------------------------------------------------------------- preconditions, on live bytes
ws_board, ws_side = os.path.join(WS, 'rl_app_data.json'), os.path.join(WS, 'rl_app_data.json.srcmd5')
side = json.load(open(ws_side))
print('THE BUILD OUTPUT THIS PUBLISHES (from the workspace, stamped by single_source.stamp_derived)')
print('  artifact md5      %s' % md5(ws_board))
print('  sidecar own_md5   %s' % side['own_md5'])
print('  sidecar source    %s' % side['source_md5'])
if md5(ws_board) != NEW_BOARD or side['own_md5'] != NEW_BOARD:
    raise SystemExit('HALT: the workspace board is not %s' % NEW_BOARD)
if side['source_md5'] != STORE or md5(P('engine/rl_after/rl_model_data.json')) != STORE:
    raise SystemExit('HALT: the sidecar/store do not both name %s' % STORE)
if md5(P('data/rl_build/rl_app_data.json')) != OLD_BOARD:
    raise SystemExit('HALT: the committed board is not %s' % OLD_BOARD)
print('  preconditions OK — the sidecar was written by the build, not by this instrument\n')

# ---------------------------------------------------------------- act 2: the boot pin, surgical
boot_p = P('data/expected_boot.json')
s = open(boot_p, encoding='utf-8').read()
needle = '"board": "%s"' % OLD_BOARD
if s.count(needle) != 1:
    raise SystemExit('HALT: expected exactly one board pin, found %d' % s.count(needle))
s_new = s.replace(needle, '"board": "%s"' % NEW_BOARD, 1)
if len(s_new.splitlines()) != len(s.splitlines()):
    raise SystemExit('HALT: line count must not change')
print('2  expected_boot.board          %s -> %s' % (OLD_BOARD[:8], NEW_BOARD[:8]))

# ---------------------------------------------------------------- act 3: the contract, own writer
RCT = _load('release_contract_334', P('release_contract.py'))
rc_p = P('data/release_contract.json')
rc = json.load(open(rc_p))
old_seal = rc['contract_sha256']
body = {k: v for k, v in rc.items() if k != 'contract_sha256'}
if RCT.contract_hash(body) != old_seal:
    raise SystemExit('HALT: the seal is not self-consistent before this act')
if rc['identities']['board'] != OLD_BOARD:
    raise SystemExit('HALT: contract board is %s' % rc['identities']['board'])
rc['identities']['board'] = NEW_BOARD
rc['contract_sha256'] = RCT.contract_hash({k: v for k, v in rc.items() if k != 'contract_sha256'})
print('3  contract identities.board     %s -> %s' % (OLD_BOARD[:8], NEW_BOARD[:8]))
print('   contract_sha256              %s -> %s' % (old_seal[:12], rc['contract_sha256'][:12]))

if not APPLY:
    print('\nDRY RUN — nothing written. (ui bundles regenerate after the pins move, by their own tool.)')
    raise SystemExit(0)

# ---------------------------------------------------------------- writes, then re-read and assert
for p in (P('data/rl_build/rl_app_data.json'), P('data/rl_build/rl_app_data.json.srcmd5')):
    os.chmod(p, stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH)
shutil.copyfile(ws_board, P('data/rl_build/rl_app_data.json'))
shutil.copyfile(ws_side, P('data/rl_build/rl_app_data.json.srcmd5'))
open(boot_p, 'w', encoding='utf-8').write(s_new)
write_json_preserving(rc_p, rc)

boot2, rc2 = json.load(open(boot_p)), json.load(open(rc_p))
side2 = json.load(open(P('data/rl_build/rl_app_data.json.srcmd5')))
assert md5(P('data/rl_build/rl_app_data.json')) == NEW_BOARD, 'board artifact did not take'
assert side2 == side, 'sidecar did not mirror byte-for-byte'
assert boot2['board'] == NEW_BOARD and boot2['store'] == STORE, 'boot pins did not take'
assert rc2['identities']['board'] == NEW_BOARD and rc2['identities']['store'] == STORE
assert rc2['contract_sha256'] == RCT.contract_hash(
    {k: v for k, v in rc2.items() if k != 'contract_sha256'}), 'seal does not verify after write'
print('\n1  data/rl_build/rl_app_data.json      %s -> %s  (+ sidecar mirrored)'
      % (OLD_BOARD[:8], NEW_BOARD[:8]))
print('PUBLISHED and re-read. Board and store identities now agree everywhere they are named.')
