#!/usr/bin/env python3
"""#328 STEP 6b — PUBLISH THE REBUILT BOARD: move the board identity where it is named.

WHY THIS EXISTS, and why it is a correction to this act's own earlier reasoning.
  At step 1 this seat left two store-identity carriers alone with a stated reason:
  `data/rl_build/*.srcmd5` and the `ui/data` bundles "are board-derived and move at a board rebuild,
  which this act never reached". The act has now reached it — step 6 rebuilt the board. Leaving them
  behind made the tree disagree with itself, and the project's own guard says so in as many words
  (`ui/tools/ownership_store_apply.py`, P3):

      INCOHERENT BASE — the six store-identity carriers disagree BEFORE any write
          store file / expected_boot.store / release_contract.identities.store /
          season_state.source_store_md5   ... all f1e8c9fe
          rl_app_data.json.srcmd5.source_md5 / board_view_working.stamp.store_md5   ... still 81d24704

  "If the tree already disagrees with itself about which store it is on, moving the pin would paper
  over the disagreement instead of surfacing it." The guard is right and the earlier deferral was
  wrong once the board rebuilt. This completes the set.

WHAT MOVES HERE, and nothing else:
    data/expected_boot.json        'board'                 f2df6e0a -> 2b7c1a00   (surgical, byte-preserving)
    data/release_contract.json     identities.board        f2df6e0a -> 2b7c1a00
                                   contract_sha256         recomputed by the contract's OWN writer

  The board artifact itself (`data/rl_build/rl_app_data.json` + `s4_matrix.json`) and their `.srcmd5`
  sidecars are the canonical build's own outputs, stamped by the artifact's own writer
  (`single_source.stamp_derived`) and mirrored in; the `ui/data` bundles are regenerated by
  `ui/tools/extract_board_view.py`, whose RING-FENCE assert refuses to run until this pin moves.

DELIBERATELY NOT MOVED: `balanced_board_md5` (4939d740). The balanced reference is a separate
artifact and the landing's own note reserves it — no balanced reference is built here.

  python3 repin_board_identity.py <REPO> [--dry-run]
"""
import importlib.util, json, os, sys

REPO = sys.argv[1].rstrip('/') if len(sys.argv) > 1 else os.getcwd()
DRY = '--dry-run' in sys.argv
P = lambda *a: os.path.join(REPO, *a)

OLD_BOARD = 'f2df6e0a2902f48e1df36f35493ba8c1'
NEW_BOARD = '2b7c1a00ee88c42e46d56ca1ccce44cd'


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m); return m


def main():
    sidecar = json.load(open(P('data/rl_build/rl_app_data.json.srcmd5')))
    assert sidecar['own_md5'] == NEW_BOARD, 'the committed board artifact is %s' % sidecar['own_md5']
    assert sidecar['source_md5'] == 'f1e8c9fed35462536d00add604f69a3f', 'sidecar names the wrong store'
    print('committed board artifact %s on store %s (sidecar written by single_source.stamp_derived)'
          % (sidecar['own_md5'][:8], sidecar['source_md5'][:8]))

    boot_p = P('data/expected_boot.json')
    s = open(boot_p, encoding='utf-8').read()
    needle = '"board": "%s"' % OLD_BOARD
    assert s.count(needle) == 1, 'expected exactly one board pin, found %d' % s.count(needle)
    s_new = s.replace(needle, '"board": "%s"' % NEW_BOARD, 1)
    assert len(s_new.splitlines()) == len(s.splitlines()), 'line count must not change'
    print('expected_boot.board            %s -> %s' % (OLD_BOARD[:8], NEW_BOARD[:8]))

    RCT = _load('release_contract_328b', P('release_contract.py'))
    rc_p = P('data/release_contract.json')
    rc = json.load(open(rc_p))
    old_seal = rc['contract_sha256']
    assert old_seal == RCT.contract_hash(rc), 'the seal must be self-consistent before this act'
    assert rc['identities']['board'] == OLD_BOARD, 'contract board %s' % rc['identities']['board']
    rc['identities']['board'] = NEW_BOARD
    rc['contract_sha256'] = RCT.contract_hash(rc)
    print('contract identities.board      %s -> %s' % (OLD_BOARD[:8], NEW_BOARD[:8]))
    print('contract_sha256                %s -> %s' % (old_seal[:8], rc['contract_sha256'][:8]))

    if DRY:
        print('\n--dry-run: nothing written.')
        return
    open(boot_p, 'w', encoding='utf-8').write(s_new)
    open(rc_p, 'w').write(json.dumps(rc, indent=1, sort_keys=True) + '\n')

    boot2 = json.load(open(boot_p)); rc2 = json.load(open(rc_p))
    assert boot2['board'] == NEW_BOARD, 'boot board pin did not take'
    assert boot2['store'] == sidecar['source_md5'], 'boot store pin must still name the store'
    assert rc2['identities']['board'] == NEW_BOARD, 'contract board pin did not take'
    assert rc2['contract_sha256'] == RCT.contract_hash(rc2), 'contract seal must verify after the write'
    print('\nRE-PINNED and re-read. The board identity now agrees everywhere it is named.')


if __name__ == '__main__':
    main()
