#!/usr/bin/env python3
"""#328 STEP 1b — RE-STAMP EVERY PIN THAT NAMES THE STORE, each as its own ordered act.

WHY THIS FILE EXISTS (#328 Addendum 1 item 1, from pre-fire audit fault 1):
  #328's body described the landing seat's copy instrument as if it also re-stamped the pins.
  It does not — install_store_323.py is hash-assert, copy, re-assert, and nothing else. The pin
  work at the landing was that seat's own separate acts, and it was never committed. A seat
  reusing the copy tool as the body described it would carry a boot pin still naming 81d24704
  into the refit. So the re-stamps are performed here as ACTS, never as an assumed side effect,
  each through the artifact's own writer, each re-read and asserted after the write.

THE ACTS, IN ORDER
  1  data/expected_boot.json   'store'                  — plain pin, re-read and asserted
  2  data/release_contract.json 'identities.store'      — plus contract_sha256 recomputed by the
                                                          contract's OWN writer (release_contract.contract_hash)
  3  data/season_state.json                             — RE-DERIVED by season_state.derive from the
                                                          new store bytes. The landing seat measured that
                                                          the dials do not move; this MEASURES it again
                                                          rather than carrying that forward as an assumption.
  4  tier-2 frozen stamps                               — regenerated by the engine's own writer
                                                          (single_source.lock_tier2), a pure function of
                                                          the artifact bytes.

DELIBERATELY NOT MOVED, each for a stated reason
  ui/release_pick_curve.json 'curve_source_store_md5' and its selftest assert
  (one_source_selftest.py FROZEN-RULER) stay at 81d24704: the field records the store the ruled
  curve was DERIVED ON, which remains true. data/release_lineage.json is sealed history.
  data/rl_build/*.srcmd5 and the ui/data bundles are board-derived and move at the board rebuild,
  not here.

  python3 restamp_store_pins.py --dry-run
  python3 restamp_store_pins.py --apply
"""
import hashlib, importlib.util, json, os, sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
STORE = os.path.join(REPO, 'engine', 'rl_after', 'rl_model_data.json')
BOOT = os.path.join(REPO, 'data', 'expected_boot.json')
CONTRACT = os.path.join(REPO, 'data', 'release_contract.json')
EXPECT_STORE = 'f1e8c9fed35462536d00add604f69a3f'


def md5(path):
    with open(path, 'rb') as f:
        return hashlib.md5(f.read()).hexdigest()


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def write_json(path, obj):
    """Preserve the file's own formatting convention exactly: 1-space indent, unicode escaped,
    and the file's existing trailing-newline habit (season_state.json carries none, the other two
    do). Proven before any write by round-tripping the untouched file byte-identically, so the
    committed diff carries the intended fields and nothing else."""
    original = open(path, 'rb').read()
    tail = '\n' if original.endswith(b'\n') else ''
    round_trip = (json.dumps(json.load(open(path)), indent=1) + tail).encode()
    if round_trip != original:
        raise SystemExit('HALT: %s does not round-trip byte-identically — a write here would '
                         'reformat the file, so nothing is written' % path)
    with open(path, 'w') as f:
        f.write(json.dumps(obj, indent=1) + tail)


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else '--dry-run'
    apply = (mode == '--apply')
    if mode not in ('--dry-run', '--apply'):
        raise SystemExit('HALT: pass --dry-run or --apply')

    store_md5 = md5(STORE)
    print('store on disk    %s  (expect %s)' % (store_md5, EXPECT_STORE))
    if store_md5 != EXPECT_STORE:
        raise SystemExit('HALT: the store is not the #323 corrected bytes — no pin is touched')

    # ---- act 1: the boot pin -------------------------------------------------
    boot = json.load(open(BOOT))
    print('\n1  expected_boot.json  store   %s -> %s' % (boot.get('store'), store_md5))
    if apply:
        boot['store'] = store_md5
        write_json(BOOT, boot)
        again = json.load(open(BOOT))
        assert again['store'] == store_md5, 'boot pin did not take'
        print('   re-read after write: %s  ASSERTED' % again['store'])

    # ---- act 2: the contract, sealed by its own writer -----------------------
    rct = _load('release_contract_328', os.path.join(REPO, 'release_contract.py'))
    con = json.load(open(CONTRACT))
    old_seal = con.get('contract_sha256')
    body = {k: v for k, v in con.items() if k != 'contract_sha256'}
    print('\n2  release_contract.json  identities.store  %s -> %s'
          % (con['identities'].get('store'), store_md5))
    print('   stored seal recomputes to %s (self-consistent: %s)'
          % (rct.contract_hash(body)[:12], rct.contract_hash(body) == old_seal))
    if apply:
        con['identities']['store'] = store_md5
        body = {k: v for k, v in con.items() if k != 'contract_sha256'}
        new_seal = rct.contract_hash(body)
        con['contract_sha256'] = new_seal
        write_json(CONTRACT, con)
        again = json.load(open(CONTRACT))
        recomputed = rct.contract_hash({k: v for k, v in again.items() if k != 'contract_sha256'})
        assert again['identities']['store'] == store_md5, 'contract store pin did not take'
        assert again['contract_sha256'] == recomputed, 'contract seal does not verify after write'
        print('   contract_sha256 %s -> %s   re-read and re-verified'
              % (old_seal[:12], again['contract_sha256'][:12]))

    # ---- act 3: the season state, re-derived and re-measured -----------------
    ss = _load('season_state_328', os.path.join(REPO, 'season_state.py'))
    cur = json.load(open(os.path.join(REPO, 'data', 'season_state.json')))
    new = ss.derive(cur['as_of_round'], STORE, season_year=cur['season_year'],
                    season_total_rounds=cur['season_total_rounds'])
    moved = {k: (cur.get(k), new.get(k)) for k in ('calendar_progress', 'exposure_pace')
             if cur.get(k) != new.get(k)}
    print('\n3  season_state.json  re-derived from the new store by season_state.derive')
    print('   calendar_progress %s -> %s   exposure_pace %s -> %s'
          % (cur['calendar_progress'], new['calendar_progress'],
             cur['exposure_pace'], new['exposure_pace']))
    print('   eligible_durable_players %s -> %s   median_current_games %s -> %s'
          % (cur['exposure_derivation']['eligible_durable_players'],
             new['exposure_derivation']['eligible_durable_players'],
             cur['exposure_derivation']['median_current_games'],
             new['exposure_derivation']['median_current_games']))
    print('   MEASURED, not assumed: valuation dials %s'
          % ('MOVE — %s' % moved if moved else 'do not move; only the source stamp does'))
    if apply:
        write_json(os.path.join(REPO, 'data', 'season_state.json'), new)
        again = json.load(open(os.path.join(REPO, 'data', 'season_state.json')))
        assert again['source_store_md5'] == store_md5, 'season state source stamp did not take'
        print('   source_store_md5 re-read: %s  ASSERTED' % again['source_store_md5'])

    # ---- act 4: the tier-2 frozen stamps ------------------------------------
    print('\n4  tier-2 frozen stamps — regenerated by the engine\'s own writer at the workspace')
    print('   (run single_source.lock_tier2() from the seeded workspace; recorded in the filing)')

    if not apply:
        print('\nDRY RUN — nothing written.')
        return
    print('\nRE-STAMPED. Every pin naming the store now reads %s.' % store_md5)


if __name__ == '__main__':
    main()
