#!/usr/bin/env python3
"""tools/probe_bundle_equality.py — the LIVENESS PROBE for final-integration's generated-bundle
equality step (`cmp` of ui/data/board_view_{working,public}.js against a fresh extract).

    python3 tools/probe_bundle_equality.py [TREE_ROOT]     exit 0 = the step would pass, 1 = fails

WHY A TOOL AND NOT AN INLINE argv. The CI step regenerates the bundles IN PLACE and compares. Run
that way from a ledger probe it would REWRITE two committed UI bundles on the live tree to answer a
question about them — a probe that moves the thing it measures. `extract_board_view.py` already
takes `RL_UI_OUT_DIR`, so this writes the fresh extract to a throwaway directory and compares
there. The tree is never written to.

WHAT IS MEASURED (2026-08-20): the regenerated `board_view_working.js` is 580 bytes SHORTER than
the committed one and drops the whole `release{}` block (`release_version`,
`balanced_board_md5` …). `board_view_public.js` reproduces byte-exact. The extractor is not the
sole writer of the working bundle — the landing act's UI writer adds the release block afterwards —
so the CI step's premise ("extract must reproduce the committed UI bundles byte-for-byte") is true
of one bundle and false of the other. That is a real red with a named cause, and the repair is a
decision about which writer owns the release block, not a one-liner. Carried as ruled-red FI1.
"""

import os
import shutil
import subprocess
import sys
import tempfile

BUNDLES = ('board_view_working.js', 'board_view_public.js')


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    root = argv[0] if argv else (os.environ.get('RL_REPO')
                                 or os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    out = tempfile.mkdtemp(prefix='bundle_eq_')
    try:
        env = dict(os.environ, RL_REPO=root, RL_UI_OUT_DIR=out)
        r = subprocess.run([sys.executable, os.path.join(root, 'ui', 'tools', 'extract_board_view.py')],
                           cwd=root, capture_output=True, text=True, timeout=300, env=env)
        if r.returncode != 0:
            print('bundle_equality: extract_board_view.py exited %d' % r.returncode)
            print((r.stdout or '') + (r.stderr or ''))
            return 1
        bad = []
        for name in BUNDLES:
            fresh = os.path.join(out, name)
            committed = os.path.join(root, 'ui', 'data', name)
            if not os.path.exists(fresh):
                bad.append('%s: the extractor wrote no such file' % name)
                continue
            a = open(fresh, 'rb').read()
            b = open(committed, 'rb').read()
            if a == b:
                print('  OK    %-24s regenerated byte-exact (%d bytes)' % (name, len(a)))
            else:
                bad.append('%s: regenerated %d bytes vs committed %d bytes — NOT byte-identical'
                           % (name, len(a), len(b)))
        for m in bad:
            print('  FAIL  %s' % m)
        print('bundle_equality: %d of %d bundles reproduce byte-exact' % (len(BUNDLES) - len(bad),
                                                                         len(BUNDLES)))
        return 1 if bad else 0
    finally:
        shutil.rmtree(out, ignore_errors=True)


if __name__ == '__main__':
    sys.exit(main())
