#!/usr/bin/env python3
"""tools/rulebook_twin.py — THE REGENERATOR docs/acceptance_v2_0.json never had (PLAN_v6 1b).

    python3 tools/rulebook_twin.py diff            what regeneration would change (writes nothing)
    python3 tools/rulebook_twin.py write [--out P]  regenerate the twin
    python3 tools/rulebook_twin.py check            exit 1 if the committed twin != regeneration

THE PROBLEM THIS ANSWERS, stated as the plan states it. `docs/acceptance_v2_0.json` declares itself
`regenerated_from: RULEBOOK.md v2.1` and IS READ AND REGENERATED BY NO CODE. It is a hand-maintained
derived laws view with no regeneration trigger and no banner — the in-tree violator of 1b's "no
second laws file, ever". 1b's disposal is owner-ruled: WIRE IT TO A REAL REGENERATOR, or REMOVE IT.
This tool is the first half, built so the owner can rule on a thing that exists rather than on a
promise.

WHAT IS DERIVED AND WHAT IS CARRIED, because the difference is the whole honesty of the file:

  DERIVED from docs/RULEBOOK.md, every run:   version, date, regenerated_from, the LAW SET and its
                                              ORDER, and the do-not-hand-edit banner.
  CARRIED from the previous twin, by law id:  each law's `check` prose and its threshold payload
                                              (`pick1_equals`, `band_scar`, `max_pct`, ...).

The carried half is measurement detail that lives nowhere else in the tree — RULEBOOK PART 3 says
how rules are checked in prose, not in numbers — so a regenerator that dropped it would destroy
information, and one that INVENTED it would be worse. Carrying it with a named provenance is the
honest third option, and the file says so in its own banner.

THE REFUSAL IS THE POINT. A law in the twin that the RULEBOOK does not number is NOT silently
dropped and NOT silently kept: regeneration REFUSES, names it, and stops. Today that fires on G-Y0
and G-COHORT — the register's standing law-count flag, which is exactly the question 1b puts to the
owner. A generator that quietly resolved it would have decided an owner-signed question by itself.
"""

import argparse
import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
sys.path.insert(0, _HERE)

import rulebook_lint as RL                                                     # noqa: E402

TWIN_REL = os.path.join('docs', 'acceptance_v2_0.json')

BANNER = ('GENERATED-ONLY — DO NOT HAND-EDIT. Regenerate with tools/rulebook_twin.py write; '
          'CI asserts equality via tools/rulebook_lint.py. THE RULEBOOK WINS: docs/RULEBOOK.md is '
          'the owner-signed single governing document and this file is a derived view of it. The '
          'per-law `check` prose and thresholds are CARRIED FORWARD from the previous twin by law '
          'id (they are measurement detail that exists nowhere else in the tree); everything else '
          'on this page is derived from the RULEBOOK on every regeneration.')


class Refusal(RuntimeError):
    pass


def _rulebook(root):
    text = open(os.path.join(root, RL.RULEBOOK_REL), encoding='utf-8').read()
    laws, numbers, unparsed = RL.parse_rulebook(text)
    if unparsed:
        raise Refusal('the RULEBOOK has %d numbered line(s) this tool cannot read: %s'
                      % (len(unparsed), unparsed[0][:80]))
    header = next((ln for ln in text.splitlines() if ln.startswith('# THE RULEBOOK')), '')
    version = date = ''
    for part in header.lstrip('# ').split('·'):
        part = part.strip()
        if part.lower().startswith('the rulebook'):
            version = part.split()[-1]
        elif part[:4].isdigit():
            date = part.split()[0]
    return laws, version, date, header


def regenerate(root, previous):
    """-> the twin document this RULEBOOK implies. Raises Refusal on an unruled law."""
    laws, version, date, header = _rulebook(root)
    prev_by_id = {}
    for law in (previous.get('laws') or []):
        prev_by_id[str(law.get('id'))] = law

    orphans = [i for i in prev_by_id if not RL.recoverable_from(i, laws)]
    if orphans:
        raise Refusal(
            'the committed twin carries %d law(s) the RULEBOOK does not number: %s. '
            'Regeneration REFUSES rather than choosing: either the RULEBOOK gains them (an '
            'owner-signed amendment, RULEBOOK law 10(a)) or they leave the twin. This is the '
            'register\'s standing law-count flag, and it is not a generator\'s to settle.'
            % (len(orphans), ', '.join(sorted(orphans))))

    out_laws = []
    for lid in laws:
        src = next((prev_by_id[k] for k in prev_by_id if RL.recoverable_from(k, [lid])), None)
        law = {'id': (src or {}).get('id', lid), 'status': (src or {}).get('status', 'BINDING')}
        for k, v in sorted((src or {}).items()):
            if k not in ('id', 'status'):
                law[k] = v
        if src is None:
            law['check'] = 'NO CARRIED CHECK — this law is new in the RULEBOOK and its measurement ' \
                           'detail has not been written yet.'
        out_laws.append(law)

    doc = {'_banner': BANNER,
           'version': version or previous.get('version'),
           'date': date or previous.get('date'),
           'status': previous.get('status', 'OFFICIAL'),
           'supersedes': previous.get('supersedes', []),
           'regenerated_from': 'docs/RULEBOOK.md %s (regenerated by tools/rulebook_twin.py)'
                               % (version or ''),
           'laws': out_laws}
    for k in ('dated_reads', 'carried_records'):
        if k in previous:
            doc[k] = previous[k]
    return doc


def _render(doc):
    return json.dumps(doc, indent=1, ensure_ascii=False) + '\n'


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('mode', choices=('diff', 'write', 'check'))
    ap.add_argument('--root', default=os.environ.get('RL_REPO') or _ROOT)
    ap.add_argument('--out', default=None, help='write target (default: the committed twin)')
    a = ap.parse_args(argv)
    root = os.path.abspath(a.root)
    twin_path = os.path.join(root, TWIN_REL)
    previous = json.load(open(twin_path, encoding='utf-8')) if os.path.exists(twin_path) else {}

    try:
        doc = regenerate(root, previous)
    except Refusal as e:
        print('REGENERATION REFUSED: %s' % e)
        return 1

    text = _render(doc)
    if a.mode == 'write':
        target = a.out or twin_path
        with open(target, 'w', encoding='utf-8') as fh:
            fh.write(text)
        print('wrote %s (%d laws)' % (target, len(doc['laws'])))
        return 0

    committed = open(twin_path, encoding='utf-8').read() if os.path.exists(twin_path) else ''
    if committed == text:
        print('twin is byte-identical to its regeneration (%d laws)' % len(doc['laws']))
        return 0
    if a.mode == 'check':
        print('twin DIFFERS from its regeneration — run tools/rulebook_twin.py write')
        return 1
    import difflib
    sys.stdout.writelines(difflib.unified_diff(
        committed.splitlines(True), text.splitlines(True),
        fromfile='a/' + TWIN_REL, tofile='b/' + TWIN_REL))
    return 0


if __name__ == '__main__':
    sys.exit(main())
